### ISSUE TITLE
Can't create pull request

### ISSUE THREAD

**Issue by GarryPatchett** [nitramr/scribus-webpage#1]
Using GitHub for Windows I created a new branch, then made some changes, then tried to create a new pull request.

I got a message that I couldn't push the changes "Sync failed to push changes, It seems you don't have permission to to push changes", then got another one saying I couldn't request a pull "Could not create a pull request, Try manually synchronizing the current branch as well as the target branch and try again."

Any idea what I'm doing wrong? It's been a while since I used GitHub and things look different. (I've also probably missed a very important step but I can't think what it is.)

**Comment by nitramr** [comment]
I found no setting to control pull requests. I have invite you as a collaborator, maybe that helps.

**Comment by GarryPatchett** [comment]
Thanks for the invite. That seems to have worked (after a bit of confusion on my part, GitHub was doing some weird stuff). I've added some example sections/images for the home page. Just to give the sort of idea of what I think should be there.
