### ISSUE TITLE
Bug reporting could be given a more prominent position

### ISSUE THREAD

**Issue by GarryPatchett** [nitramr/scribus-webpage#12]
One option would be to swap the Bug Report and Donate sections on the Contribute page.

**Comment by nitramr** [comment]
Done in https://github.com/nitramr/scribus-webpage/commit/ea17b99a4956c4f7c6d6631e71cb557f8851c4de

**Comment by GarryPatchett** [comment]
Good for me.

**Comment by GarryPatchett** [comment]
Closing the issue since it's been done.
