### ISSUE TITLE
The Wiki isn't really mentioned

### ISSUE THREAD

**Issue by GarryPatchett** [nitramr/scribus-webpage#13]
There's a "hidden" link to it on the Learn page but that's about it.
I know the wiki isn't great but there is a lot of good information in there so it should have its own link somewhere.

**Comment by nitramr** [comment]
Added in learn section: https://github.com/nitramr/scribus-webpage/commit/ad83f7a94dad3fe372cbacabc282ff0bf485f8c3

**Comment by GarryPatchett** [comment]
The site is looking really nice now. Obviously there are still correct links to be added in various places but I think it might be worth adding a post to the relevant thread to tell people that it's still being updated. (People generally won't go back to look if you don't tell them it's changed.)

Might also be worth modifying the post that first introduced the site - I can't modify it myself - to say that some of the comments after the initial introduction have already been taken into account and changes have been made. (Just in case people get confused about comments that are no longer relevant.)

**Comment by GarryPatchett** [comment]
Think this issue can be closed now so I'll close it.
