### ISSUE TITLE
Should we link to non-English communities?

### ISSUE THREAD

**Issue by GarryPatchett** [nitramr/scribus-webpage#15]
On the Learn page we might want to give links to the communities in non-English languages:
German - https://www.scribus-user.de/
French - Don't know the link yet
Brazilian - Don't know the link yet

**Comment by aoloe** [comment]
french: http://www.linuxgraphic.org/forums/viewforum.php?f=20

**Comment by nitramr** [comment]
I can think about two options:
1. if we would have a language switch we can show prefered content like language specific resources.
2. below the english content we add a new section for "other language" content which is related to the page, like 'learn'.

**Comment by nitramr** [comment]
I have added option two in: https://github.com/nitramr/scribus-webpage/commit/d571332314af2705f3fbe8f89e112ee3955940f6

**Comment by GarryPatchett** [comment]
Nice. Does the job very well.

**Comment by GarryPatchett** [comment]
Closing the issue because it's been done.
