### ISSUE TITLE
Extend the learn section

### ISSUE THREAD

**Issue by aoloe** [nitramr/scribus-webpage#16]
- [The Floss Manual](http://write.flossmanuals.net/scribus/introduction/)
- [The Floss Manual in French](https://fr.flossmanuals.net/scribus/introduction/) (the original one)

**Comment by GarryPatchett** [comment]
Nice, thanks. These should definitely be added.

**Comment by nitramr** [comment]
English version is added here: https://github.com/nitramr/scribus-webpage/commit/1e40089d2bc7950594b7b34668207caa465f6a98

I close this issue. If we think about a localisation of the webpage we can switch to a translated version of specific resources.
