### ISSUE TITLE
Get Involved section in footer needs changing

### ISSUE THREAD

**Issue by GarryPatchett** [nitramr/scribus-webpage#7]
Link to report a bug is needed.

Could be changed to:

- Write some code
- Change the interface
- Get the message out
- Write some docs
- Report a bug

Or something like that.

**Comment by nitramr** [comment]
Done in https://github.com/nitramr/scribus-webpage/commit/ea17b99a4956c4f7c6d6631e71cb557f8851c4de

**Comment by GarryPatchett** [comment]
Nice.

**Comment by GarryPatchett** [comment]
Closing the issue because it's been done.
