### ISSUE TITLE
Sponsors should be shown on the home page

### ISSUE THREAD

**Issue by GarryPatchett** [nitramr/scribus-webpage#9]
The project sponsors are importand so they should have a place on the home page.
A short (height) carousel might be a good idea for this.

**Comment by nitramr** [comment]
First version added here: https://github.com/nitramr/scribus-webpage/commit/8146d59c0a1bc8bf974a676fba00a974d15d5534

A slider with unified icon height could be better.

**Comment by GarryPatchett** [comment]
I've just synced up with the latest version and it looks okay to me.
Some kind of animated thing showing one at a time might be better - if that what a slider is - but I would say that what's there is fine for now.

**Comment by nitramr** [comment]
There is no slider in new commit, but looks nicer now. https://github.com/nitramr/scribus-webpage/commit/ceeaf93b0718ff017ebd2e47a74df521ec35cec6

**Comment by GarryPatchett** [comment]
Much nicer. Easily good enough for me. Probably no need for extra complexity.
